num = int(input("what is your number? \n"))
print("the number is " + str(num))
print("5 times the number is " + str(num * 5))
print("If you add 3 to " + str(num) + " the answer is " + str(num + 3))
print(f"if you divide {num} by 20 the answer is {num/20}")